backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads" 

collections:
  - name: settings
    label: Settings
    delete: false
    files:
      - name: mapbox
        label: Mapbox Settings
        file: _data/settings/mapbox.json
        fields: 
          - label: mapbox
            name: mapbox 
            widget: mapbox
      - name: sections 
        label: Section Order
        file: _data/settings/order.json
        fields:
          - label: Section Order
            name: order
            widget: ncw-reorder
            collection: sections 
            id_field: id 
            display_template: '{{id}} | {{title}}'

  - name: sections
    label: Map Sections
    folder: _data/sections
    editor: 
      preview: false
    create: true
    slug: "{{id}}"
    extension: 'json'
    fields: 
      - label: id
        name: id
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Visible Map Layers
        name: layerOpacity
        widget: ncw-file-relation
        collection: settings
        file: mapbox 
        target_field: mapbox.layers
        id_field:  id
        display_fields: id
        multiple: true
      - label: Bounds
        name: bounds
        widget: string
      - label: Pitch
        name: pitch
        widget: number
        valueType: float
        required: false
        default: 0
      - label: Bearing
        name: bearing
        widget: number
        valueType: float
        required: false
        default: 0
      - label: Content
        name: content
        widget: list
        allow_add: true
        types: 
          - label: Image
            name: image 
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
          - label: Text
            name: text 
            widget: text
            fields:
              - {label: Text, name: text, widget: text}
          - label: Video
            name: video
            widget: object
            fields:
              - {label: URL, name: url, widget: string}
              - {label: "Play in the background?", name: background, widget: boolean, default: true}
              - {label: "Placeholder Image", name: placeholderImg, widget: image}
