backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow
  site_url: https://sinangoe-map.ddem.us

local_backend: true

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads" 

collections:
  - name: settings
    label: Settings
    delete: false
    files:
      - name: mapbox
        label: Mapbox Settings
        file: _data/settings/mapbox.json
        fields: 
          - label: mapbox
            name: mapbox 
            widget: string
      - name: sections 
        label: Section Order
        file: _data/settings/order.json
        fields:
          - label: Section Order
            name: order
            widget: ncw-reorder
            collection: sections 
            id_field: id 
            display_template: '{{title}}'

  - name: sections
    label: Map Sections
    folder: _data/sections
    editor: 
      preview: false
    summary: "{{title}}"
    create: true
    slug: "{{id}}"
    extension: 'json'
    fields: 
      - label: id
        name: id
        prefix: section
        widget: ncw-id
      - label: Titulo (ES)
        name: title
        widget: string
      - label: Title (EN)
        name: title_en
        widget: string
      - label: Visible Map Layers
        name: layerOpacity
        widget: mapbox-layer-picker
        collection: settings
        file: mapbox 
        target_field: mapbox
        id_field: id
        display_fields: id
        multiple: true
      - label: Min Lat
        name: minLat
        widget: number
        valueType: float
        pattern: ['^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$', 'Must be between -90 and 90']
      - label: Max Lat
        name: maxLat
        widget: number
        valueType: float
        pattern: ['^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$', 'Must be between -90 and 90']
      - label: Min Lon
        name: minLon
        widget: number
        valueType: float
        pattern: ['^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$', 'Must be between -180 and 180']
      - label: Max Lon
        name: maxLon
        widget: number
        valueType: float
        pattern: ['^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$', 'Must be between -180 and 180']
      - label: Pitch
        name: pitch
        widget: number
        valueType: float
        required: false
        default: 0
      - label: Bearing
        name: bearing
        widget: number
        valueType: float
        required: false
        default: 0
      - label: Content
        name: content
        widget: list
        allow_add: true
        types: 
          - label: Image
            name: image 
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
          - label: Text
            name: text 
            widget: object
            fields:
              - {label: ES, name: es, widget: markdown}
              - {label: EN, name: en, widget: markdown, required: false}
          - label: Video
            name: video
            widget: object
            fields:
              - {label: URL, name: url, widget: string}
              - {label: "Play in the background?", name: background, widget: boolean, default: true}
              - {label: "Placeholder Image", name: placeholderImg, widget: image}
