backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads" 

collections:
  - name: sections
    label: Map Sections
    folder: _data/sections
    create: true
    slug: "{{slug}}"
    extension: 'json'
    fields: 
      - label: Slug
        name: slug
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Visible Map Layers
        name: layerOpacity
        widget: relation
        collection: mapLayers
        valueField: name
        searchFields: [name]
        multiple: true
        required: false
      - label: Bounds
        name: bounds
        widget: string
      - label: Content
        name: content
        widget: list
        allow_add: true
        types: 
          - label: Image
            name: image 
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
          - label: Text
            name: text 
            widget: text
            fields:
              - {label: Text, name: text, widget: text}
          - label: Video
            name: video
            widget: object
            fields:
              - {label: URL, name: url, widget: string}
              - {label: "Play in the background?", name: background, widget: boolean, default: true}
              - {label: "Placeholder Image", name: placeholderImg, widget: image}
  - name: mapLayers
    label: Map Layers
    folder: _data/layers
    create: true
    slug: "{{name}}"
    fields: 
      - {label: Name, name: name, widget: string}
      
