backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads" 

collections:
  - name: settings
    label: Settings
    delete: false
    files:
      - name: mapLayers
        label: Map Layers
        file: _data/settings/layers.json
        fields: 
          - label: layers
            name: Layers
            widget: list
            fields:
              - {label: Layer id, name: id, widget: string}
              # unsure if this is needed:
              # - {label: Default Opacity, name: opacity, widget: string, default: '0', pattern: ['^(?:0*(?:\.\d+)?|1(\.0*)?)$', 'Must be a number betwen 0 and 1']}
      
      - label: Section Order
        file: _data/settings/order.json
        name: order
        widget: ncw-reorder
        collection: sections 
        editor:
          preview: true
        id_field: id
        display_template: '{{id}} | {{title}}'
        fields:
          - { label: "Id", name: "id", widget: "string" }
  - name: sections
    label: Map Sections
    folder: _data/sections
    editor: 
      preview: false
    create: true
    slug: "{{slug}}"
    extension: 'json'
    fields: 
      - label: Title
        name: title
        widget: string
      - label: Visible Map Layers
        name: layerOpacity
        widget: relation
        collection: settings
        displayField: mapLayers.layers.id
        valueField: mapLayers.layers.id
        searchFields: [mapLayers.layers.id]
        multiple: true
        required: false
      - label: Bounds
        name: bounds
        widget: string
      - label: Content
        name: content
        widget: list
        allow_add: true
        types: 
          - label: Image
            name: image 
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
          - label: Text
            name: text 
            widget: text
            fields:
              - {label: Text, name: text, widget: text}
          - label: Video
            name: video
            widget: object
            fields:
              - {label: URL, name: url, widget: string}
              - {label: "Play in the background?", name: background, widget: boolean, default: true}
              - {label: "Placeholder Image", name: placeholderImg, widget: image}
