backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: sections
    label: Map Sections
    folder: _data/sections
    create: true
    slug: "{{slug}}"
    fields: 
      - label: Title
        name: title
        widget: string
      - label: Visible Map Layers
        name: layerOpacity
        widget: relation
        collection: MapLayers
        valueField: name
        multiple: true
      - label: Bounds
        name: bounds
        widget: string
      - label: Content
        name: content
        widget: list
        allow_add: true
        fields: 
          - {label: Image, name: image, widget: image}
          - label: Video
            name: video
            widget: object}
            fields:
              - {label: URL, name: url, widget: string}
              - {label: "Play in the background?", name: background, widget: boolean, default: true}
              - {label: "Background?", name: background, widget: boolean, default: true}
              - {label: "Placeholder Image", name: placeholderImg, widget: string}
          - {label: Text, name: text, widget: text}
  - name: mapLayers
    label: Map Layers
    folder: _data/layers
    create: true
    slug: "{{name}}"
    fields: 
      - {label: Name, name: name, widget: string}
      
